# -*- coding: utf-8 -*-
"""Hertzsprung-Russell Diagram.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D1Mh4IEQ1Z26Xfbbl2s91IiPW5olJJpc
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv("star_dataset.csv")

print(data.head())

print(data.describe())

print(data.columns)

plt.scatter(data['Temperature (K)'], data['Absolute magnitude(Mv)'], c=data['Radius(R/Ro)'].astype('category').cat.codes, cmap='rainbow')
plt.xlabel('Temperature (K)')
plt.ylabel('Absolute Magnitude')
plt.title('Hertzsprung-Russell Diagram')
plt.show()